#!/bin/sh

tag="###chen3feng-devenv###"

get_this_dir() {
  local this_dir="$(cd $(dirname $0) && pwd)"
  echo $this_dir
}

install() {
  local this_dir
  this_dir=$(get_this_dir)
  local command="$1"
  local from="$this_dir/$2"
  local to="$3"
  local comment="$4"
  local stmt="$command $from  $comment $tag"
  if [ -e $to ] && grep "$tag" "$to" > /dev/null; then
    sed -i -e "s|.*$tag.*|$stmt|g" $to
  else
    echo "$stmt" >> $to
  fi
}

install source _bashrc ~/.bashrc "#"
install source _zshrc ~/.zshrc "#"
install source _vimrc ~/.vimrc '"'
install "\$include" _inputrc ~/.inputrc "#"
