#!/bin/bash

tag="###chen3feng-devenv###"
this_dir="$(cd $(dirname $0) && pwd)"

install() {
  local command="$1"
  local from="$this_dir/$2"
  local to="$3"
  local comment="$4 $tag"
  local stmt="$command $from"
  if [ -e $to ] && grep "$comment" "$to" > /dev/null; then
    # Find the tag line
    local lineno=$(grep -n -m1 "$comment" "$to" | cut -f1 -d:)
    let lineno++
    sed -i "${lineno}s|.*|$stmt|g" $to # Replace next line of tag line
  else
    echo "$comment" >> $to
    echo "$stmt" >> $to
  fi
  echo "$to is updated."
}

install source _bashrc ~/.bashrc "#"
install source _zshrc ~/.zshrc "#"
install source _vimrc ~/.vimrc '"'
install "\$include" _inputrc ~/.inputrc "#"

$this_dir/git/install

# Install the `vim-plug` plug manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
