#!/bin/bash

HOOK_NAME=$1
shift
GLOBAL_HOOKS_DIR=$(dirname $0)

run_repository_hooks() {
    if [[ -x .git/hooks/$HOOK_NAME ]]; then
        local hook=.git/hooks/$HOOK_NAME
        $hook
        ret=$?
        if [ $ret -ne 0 ]; then
            echo "$hook exited $ret" > /dev/stderr
            exit $ret
        fi
    fi
}

# Run hooks under `HOOK_NAME.d` dirs
run_hooks_plugins() {
    local PLUGIN_DIR=$GLOBAL_HOOKS_DIR/$HOOK_NAME.d
    if [ -d $PLUGIN_DIR ]; then
        # allows patterns which match no files to expand to a null string, rather than themselves
        shopt -s nullglob
        for hook in $PLUGIN_DIR/*; do
            echo CCC $hook
            # Ignore non-executable or files starts with "_"
            if [[ ! -x $hook || $(basename $hook) == _* ]]; then
                continue
            fi
            $hook
            local ret=$?
            if [[ $ret -ne 0 ]]; then
                echo "$hook exited $ret" > /dev/stderr
                exit $ret
            fi
        done
    fi
}

run_repository_hooks
run_hooks_plugins

# For debuging dry run
# exit 1
